### ISSUE TITLE
Commands Break Everything

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Witixin1512/ArmorSetEffects#4]
Minecraft Version: 1.16.5
Forge Version: 36.2.9
CraftTweaker Version: 1.16.5-7.1.2.457
Armor Set Effects Version: 1.16.5-1.0.5

Problem: Using "/time set day" causes ArmorSetEffects to reload every ~5 ticks instead of every 5 seconds. Relogging does not fix this. Using the command "/gamerule doDaylightCycle false" disables ArmorSetEffects. There may be other random commands that break things, but those are the two that I found.

Expected Behavior: I expect that no vanilla commands should change the way Armor Set Effects works.

To replicate:
1: Install CraftTweaker
2: Install Armor Set Effects
3: Load up default Armor Set Effects script
4: Use one of the aforementioned commands in game, and see how they change Armor Set Effects.

**Comment by Witixin1512** [comment]
I know what's causing this, i'm pushing another fix now

**Comment by RobertHDPotatoes** [comment]
Awesome, it's fixed for me in the latest version. Just a quick question, how do I make it so particles don't show? Sorry, I'm pretty bad with CraftTweaker :(

**Comment by Witixin1512** [comment]
`MCPotionEffectInstance.hideParticles()`
Basically attach `hideParticles()` to your `newInstance()` method, at the end of it. Since it returns the same MCPotionEffect instance you can supply that in the addEffect method. If that doesn't work and there's no more bugs, feel free to post your thing in the crafttweaker server, i'm gonna go to sleep soon but as long as you link the docs page someone else might answer
