### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by megagnarxd** [Witixin1512/ArmorSetEffects#6]
1. Instance ticks doesn't work with /reload. (not sure about the strength of the effects)
2. Set effect is not instance. For example, if I have effect speed on 20 ticks, it will not be a permanent effect, but rather have on and off uptime. 
3. Effect doesn't go away immediately even if you take off the armor set

**Comment by megagnarxd** [comment]
Just noticed you've fixed #2. So ignore that

**Comment by Witixin1512** [comment]
1. Are you sure about that? I don't touch the effects, I just add them. Reloading applies the changes fine on my instance. I only have ArmorSetEffects1.0.6 and Crafttweaker (Forge 36.2.0)
2. That's because the effects are applied every 5 seconds, to reduce lag. Make your effects have a length of 6 secs (or 120 ticks) to make sure it's permanent and the effect is removed whenever you remove the armor
3. It depends on how close you are to the 5 second interval.

**Comment by megagnarxd** [comment]
Oops, i meant you fixed #1. #2 and #3 doesn't work. But knowing that know, I will make the appropriate changes

**Comment by Witixin1512** [comment]
Let me know if there's anything I missed!
